services:
  app:
    container_name: blogapp-backend-app
    image: blogapp-backend-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/app/node_modules/
  postgres:
    container_name: blogapp-backend-postgres
    attach: false
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
  busybox:
    container_name: blogapp-backend-busybox
    image: busybox
    